case 'shadow':
case 'banner':
case 'flaming':
case 'rainbow':
case 'smoke':
case 'love':
case 'wood':
case 'stars':
case 'coffee':
case 'butterfly':
case 'summer':
case 'candy':
case 'royal':
case 'paper':
case 'fur':
case 'joker':
case 'blackpink':
case 'neon':
case 'devil':
case 'matrix':
case 'transformers':
case 'thunder':
case 'grafity':
case 'grafity':
case 'harry':
